### ISSUE TITLE
Update README.md to make 'simply pass in a list or glob of PDF filenames' statement more clear

### ISSUE THREAD

**Issue by JohannesWiesner** [jdmonaco/pdf-title-rename#5]
When I first wanted to use the script I struggled with understanding the sentence 'simply pass in a list or glob of PDF filenames' in the README.md file. I thought I had to pass in something like [foo.pdf, bar.pdf] or ['foo.pdf', 'bar.pdf']. I am not sure if I could/should have known that (maybe I am the only one who got that wrong, I never used a parser script before). If not, it would be nice to make this more clear in the README.md file.

**Comment by jdmonaco** [comment]
Hi, yes I saw your other issue. I'm sorry for the confusion! A "glob" pattern refers to using the shell wildcard characters (`*` or `?`) to automatically expand into a list of files. It sounds like you figured it out, but something like `pdf-title-rename folderpath/*pdf` should process all those files. I will clarify the readme file. Thanks for letting me know.

**Comment by JohannesWiesner** [comment]
Ah, I see! Thanks for the explanation :)
