### ISSUE TITLE
Allow script to take folderpath as argument

### ISSUE THREAD

**Issue by JohannesWiesner** [jdmonaco/pdf-title-rename#6]
It would be nice if one could just point to a folderpath which contains mutliple .pdf files which are supposed to be renamed. This is especially useful when you download a .zip file with lots of .pdf files (i.e. most journals allow you to download the specific paper you were looking for + a bunch of other papers which are related to this paper). With the current script I have to type in all the filenames which can be quite annoying when you got a folder which contains something like: foo123_456.pdf, bar_789.pdf, etc., etc.

**Comment by jdmonaco** [comment]
Cf. #5
