### ISSUE TITLE
TypeError in get_xmp_metadata() function

### ISSUE THREAD

**Issue by seantey** [jdmonaco/pdf-title-rename#7]
For some reason when running the script on some of my pdf files, I get the following error:

```
Traceback (most recent call last):
  File "./pdf-title-rename.py", line 247, in <module>
    sys.exit(RenamePDFsByTitle(args).main())
  File "./pdf-title-rename.py", line 63, in main
    title, author = self._get_info(f)
  File "./pdf-title-rename.py", line 144, in _get_info
    xmpt, xmpa = self._get_xmp_metadata()
  File "./pdf-title-rename.py", line 207, in _get_xmp_metadata
    t = md['dc']['title']['x-default']
TypeError: string indices must be integers
```
To fix the issue, I added this bit of code to the get_xmp_metadata() function:
```
except TypeError:
    t = md['dc']['title']
```

The end result would be:
_Code begins on Line 198_
```
    def _get_xmp_metadata(self):
        t = a = None
        metadata = resolve1(self.doc.catalog['Metadata']).get_data()
        try:
            md = xmp_to_dict(metadata)
        except:
            return t, a
        try:
            t = md['dc']['title']['x-default']
        except TypeError:
            t = md['dc']['title']
        except KeyError:
            pass
```

It probably has something to do with the 'x-default' element not existing for whatever reason but I was happy enough with the quick and easy fix.

**Comment by seantey** [comment]
Funny coincidence, one of the papers I was trying to rename is an fMRI ML paper which seems like it would be something in your area of interest.

**Comment by jdmonaco** [comment]
Thanks for finding and patching this bug! Your fix should work in many cases, but I would like to add an additional test to make sure the 'title' element is a valid string (which may need to be decoded). Could you point me to this fMRI paper (or attach it to a reply) so I can validate a fix before committing? 

(Most of my work is in single-unit electrophys... for some reason I've never trusted the BOLD response!)

**Comment by seantey** [comment]
Here's a few of them that seem to have this problem. Glad I could help! Also, thank you because this saves me from the annoyance of copy pasting and renaming the papers individually.

[1-s2.0-S0920996414006021-main.pdf](https://github.com/jdmonaco/pdf-title-rename/files/3227845/1-s2.0-S0920996414006021-main.pdf)
[1-s2.0-S1053811912002893-main.pdf](https://github.com/jdmonaco/pdf-title-rename/files/3227846/1-s2.0-S1053811912002893-main.pdf)
[1-s2.0-S1053811912005459-main.pdf](https://github.com/jdmonaco/pdf-title-rename/files/3227847/1-s2.0-S1053811912005459-main.pdf)

**Comment by jdmonaco** [comment]
Thanks and good luck with the pile of papers!
