### ISSUE TITLE
Could not find metadata in the file

### ISSUE THREAD

**Issue by Sunshine352** [jdmonaco/pdf-title-rename#8]
Processing "s/@arXiv1904.09146 .pdf":
 -- Could not find metadata in the file
Processing "s/@arXiv1904.09709 .pdf":
 -- Could not find metadata in the file
Processing "s/@arXiv1904.11272 .pdf":
 -- Could not find metadata in the file
Processing "s/@arXiv1905.03333 .pdf":
 -- Could not find metadata in the file
Processing "s/@arXiv1905.11736 .pdf":
 -- Could not find metadata in the file
Processing "s/@arXiv1906.00335 .pdf":
 -- Could not find metadata in the file
Processing "s/@arXiv1906.06919 .pdf":
 -- Could not find metadata in the file
Processed 29 files:
 - Renamed: 0
 - Missing metadata: 29
 - Errors: 0

**Comment by jdmonaco** [comment]
I checked a couple of those files and, yes, they do not contain any metadata. This script can't do anything if the files don't have metadata in either the standard PDF stream or the XMP namespace. Sorry for the inconvenience!
